spring:
  data:
    cassandra:
      keyspace-name: main
      username: PLpIsTWrapYOYDbQtUAthjLr
      password: 
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: dynamicscheduler
server:
  servlet:
    context-path: /dynamicscheduler
      
datastax.astra:
  secure-connect-bundle: secure-connect-mydatabase.zip
astra:
  db:
    id: 15a5cc0e-2924-4e34-afad-980eb9f3d727-1
    region: us-east1
    keyspace: main
    application.token: 

      
